### ISSUE TITLE
NVM abbreviation

### ISSUE THREAD

**Issue by ipatch** [rsilvestre/phoenix-react-redux-starter-kit#17]
Hello, just wanted to let you know that NVM stands for Node Version Manager NOT Node Virtual Machine.  You call it Node Virtual Machine in your Readme.

Happy Holidays.

**Comment by rsilvestre** [comment]
Hi ipatch,

Thank you to report me this error.

**Comment by rsilvestre** [comment]
fixed https://github.com/rsilvestre/phoenix-react-redux-starter-kit/pull/18
